#! /bin/sh
# vim:et:ft=sh:sts=2:sw=2
#
# Copyright 2020 Kate Ward. All Rights Reserved.
# Released under the Apache 2.0 license.
#
# Author: kate.ward@forestent.com (Kate Ward)

# shlib_expr_cmd determines a reasonable default `expr` command.
# https://github.com/kward/shlib
#
# Use like:
#   EXPR_CMD=$(shlib_expr_cmd)
#   ${EXPR_CMD} 1 + 1
#
# Args:
#   none
# Output:
#   string: expr command
# Return
#   int: 0 upon success
shlib_expr_cmd() {
  if [ "$(uname -s)" = 'BSD' ]; then
    echo 'gexpr --'
    return 0
  fi

  _shlib_expr_cmd_='expr --'
  # shellcheck disable=SC2003
  if _shlib_output_=$(${_shlib_expr_cmd_} 2>&1); then
    if [ "${_shlib_output_}" = '--' ]; then
      # We are likely running inside BusyBox.
      _shlib_expr_cmd_='expr'
    fi
  fi

  echo "${_shlib_expr_cmd_}"
  unset _shlib_expr_cmd_ _shlib_output_
}
